export const TREE_DATA = [
    {
        id: 'output-folder',
        name: 'Outputs',
        type: 'folder',
        children: [
            { id: 'output-node', name: 'Output Node', type: 'output' },
        ],
    },
    {
        id: '1',
        name: 'Node Types',
        type: 'folder',
        children: [
            { id: '3', name: 'Calculation Node', type: 'calculation' },
            { id: '4', name: 'Condition Node', type: 'condition' },
            { id: '5', name: 'Case Range', type: 'case-range' },
            { id: '6', name: 'Case Value', type: 'case-value' },
            { id: '109', name: 'Case Default', type: 'case-default' },
            { id: '7', name: 'Switch Node', type: 'switch' },
            { id: '8', name: 'If Node', type: 'node' },
        ],
    },
    {
        id: '9',
        name: 'Elements & Values',
        type: 'folder',
        children: [
            { id: '10', name: 'Element Node', type: 'element' },
            { id: '112', name: 'Element ID Node', type: 'element-id' },
            { id: '110', name: 'Element Reference', type: 'element-ref' },
            { id: '111', name: 'Element Property', type: 'element-property' },
            { id: '11', name: 'Number Constant', type: 'number' },
            { id: '12', name: 'Boolean Constant', type: 'constant-boolean' },
            { id: '13', name: 'String Constant', type: 'constant-string' },
        ],
    },
    {
        id: '33',
        name: 'Boolean Logic',
        type: 'folder',
        children: [
            { id: '34', name: 'NOT', type: 'not' },
            { id: '35', name: 'AND', type: 'and' },
            { id: '36', name: 'OR', type: 'or' },
            { id: '65', name: 'Fallback', type: 'fallback' },
        ],
    },
    {
        id: '37',
        name: 'Math',
        type: 'folder',
        children: [
            { id: '38', name: 'Clamp', type: 'clamp' },
            { id: '39', name: 'Min', type: 'min-val' },
            { id: '40', name: 'Max', type: 'max-val' },
        ],
    },
    {
        id: '14',
        name: 'String Logic',
        type: 'folder',
        children: [
            { id: '16', name: 'Concat', type: 'concat' },
            { id: '17', name: 'Cut — Remove Found Text', type: 'cut-a' },
            { id: '18', name: 'Cut — Text Before Index', type: 'cut-b' },
            { id: '19', name: 'Cut — Text Between Indexes', type: 'cut-c' },
            { id: '20', name: 'Count Characters', type: 'string-count-chars' },
            { id: '26', name: 'String To Number', type: 'string-to-number' },
            { id: '27', name: 'Number To String', type: 'number-to-string' },
            { id: '43', name: 'Trim', type: 'string-trim' },
            { id: '44', name: 'Uppercase', type: 'string-upper' },
            { id: '45', name: 'Lowercase', type: 'string-lower' },
            { id: '46', name: 'Includes', type: 'string-includes' },
        ],
    },
    {
        id: '28',
        name: 'Colors',
        type: 'folder',
        children: [
            { id: '29', name: 'Color Node', type: 'color' },
        ],
    },
    {
        id: '48',
        name: 'CSS',
        type: 'folder',
        children: [
            { id: '49', name: 'CSS Unit (px/%/em...)', type: 'css-unit' },
            { id: '71', name: 'CSS Margin', type: 'css-margin' },
            { id: '72', name: 'CSS Padding', type: 'css-padding' },
            { id: '73', name: 'CSS Width', type: 'css-width' },
            { id: '74', name: 'CSS Height', type: 'css-height' },
            { id: '75', name: 'CSS Font Size', type: 'css-font-size' },
            { id: '50', name: 'CSS Display', type: 'css-display' },
            { id: '51', name: 'CSS Color', type: 'css-color' },
            { id: '52', name: 'CSS Text', type: 'css-text' },
            { id: '70', name: 'CSS Join', type: 'css-join' },
        ],
    },
    {
        id: '76',
        name: 'Array',
        type: 'folder',
        children: [
            { id: '77', name: 'Array', type: 'array' },
            { id: '78', name: 'Push', type: 'array-push' },
            { id: '79', name: 'Pop Out', type: 'array-pop' },
            { id: '80', name: 'Sort', type: 'array-sort' },
            { id: '81', name: 'Remove by Index', type: 'array-remove-index' },
            { id: '82', name: 'Replace by Index', type: 'array-replace-index' },
            { id: '200', name: 'Map', type: 'array-map' },
            { id: '201', name: 'Filter', type: 'array-filter' },
            { id: '202', name: 'Reduce', type: 'array-reduce' },
            { id: '203', name: 'Find', type: 'array-find' },
            { id: '204', name: 'For Each', type: 'array-for-each' },
            { id: '205', name: 'Collect Results', type: 'array-collect' },
            { id: '206', name: 'Contains', type: 'array-contains' },
            { id: '207', name: 'Length', type: 'array-length' },
            { id: '208', name: 'Merge', type: 'array-merge' },
            { id: '209', name: 'Unique', type: 'array-unique' },
        ],
    },
    {
        id: '83',
        name: 'Image',
        type: 'folder',
        children: [
            { id: '84', name: 'Image From Link', type: 'image-from-link' },
            { id: '85', name: 'Image From Element', type: 'image-from-element' },
        ],
    },
    {
        id: '61',
        name: 'Events',
        type: 'folder',
        children: [
            { id: '62', name: 'Event Element Node', type: 'event-element' },
            { id: '63', name: 'Event ID Node', type: 'event-id' },
            { id: '64', name: 'Event Processor', type: 'event-processor' },
            { id: '210', name: 'Hover Event', type: 'event-hover' },
            { id: '211', name: 'Scroll Event', type: 'event-scroll' },
            { id: '212', name: 'Page Load', type: 'event-page-load' },
            { id: '213', name: 'Timer', type: 'event-timer' },
            { id: '214', name: 'Custom Event', type: 'event-custom' },
        ],
    },
    {
        id: '98',
        name: 'Actions',
        type: 'folder',
        children: [
            { id: '99', name: 'Action Event Node', type: 'action-event' },
            { id: '100', name: 'Action Block Node', type: 'action-block' },
            { id: '101', name: 'Set Required', type: 'action-required' },
            { id: '102', name: 'Set Min', type: 'action-min' },
            { id: '103', name: 'Set Max', type: 'action-max' },
            { id: '104', name: 'Set Length', type: 'action-length' },
            { id: '105', name: 'Set Regex', type: 'action-regex' },
            { id: '106', name: 'Add Class', type: 'action-add-class' },
            { id: '107', name: 'Remove Class', type: 'action-remove-class' },
            { id: '108', name: 'Toggle Class', type: 'action-toggle-class' },
            { id: '220', name: 'Set Text', type: 'action-set-text' },
            { id: '221', name: 'Set HTML', type: 'action-set-html' },
            { id: '222', name: 'Set Value', type: 'action-set-value' },
            { id: '223', name: 'Set Attribute', type: 'action-set-attr' },
            { id: '224', name: 'Set Style', type: 'action-set-style' },
            { id: '225', name: 'Set Visibility', type: 'action-set-visibility' },
            { id: '226', name: 'Enable Element', type: 'action-enable' },
            { id: '227', name: 'Disable Element', type: 'action-disable' },
            { id: '228', name: 'Focus Element', type: 'action-focus' },
            { id: '229', name: 'Scroll To Element', type: 'action-scroll-to' },
            { id: '230', name: 'Show Notification', type: 'action-notify' },
            { id: '231', name: 'Redirect', type: 'action-redirect' },
            { id: '232', name: 'Trigger Event', type: 'action-trigger-event' },
        ],
    },
];
